# https://docs.github.com/en/actions/sharing-automations/creating-actions/publishing-actions-in-github-marketplace
name: "Setup Iggy server"
author: "Tchoupinax"
description: "A GitHub Action to run iggy server"
inputs:
  version:
    description: "The Iggy version to launch."
    required: false
    default: "0.4.72"
outputs:
  version:
    description: "The Iggy version that was launched."
runs:
  using: "node20"
  main: "dist/index.js"
# https://actions-cool.github.io/github-action-branding
branding:
  icon: "box"
  color: "orange"
