name: Write changelog
on:
  push:
    tags:
      - "v*"

jobs:
  create-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ steps.app-token.outputs.token }}
          tag: ${{ github.ref_name }}
          restrictToTypes: ""
          reverseOrder: true
          excludeTypes: ""
          excludeScopes: ""

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
          file_pattern: CHANGELOG.md

      - name: Update major tag to ${{ github.ref_name }}
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ github.ref_name }}
