name: Update major tag
on:
  push:
    tags:
      - "v*"

jobs:
  create-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Update major tag to ${{ github.ref_name }}
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ github.ref_name }}
